apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/deployment.yaml
  - resources/service.yaml

configMapGenerator:
  - name: champ-user-consumer-configmap-file
    files:
    - configs/config.yaml

secretGenerator:
  - name: champ-user-consumer-secret-env
    envs:
    - secrets/secret.env

namespace: training-champ