apiVersion: apps/v1
kind: Deployment
metadata:
  name: champ-user-consumer
  labels:
    app.kubernetes.io/name: champ-user-consumer
    app.kubernetes.io/instance: champ-user-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: champ-user-consumer
      app.kubernetes.io/instance: champ-user-consumer
  template:
    metadata:
      labels:
        app.kubernetes.io/name: champ-user-consumer
        app.kubernetes.io/instance: champ-user-consumer
    spec:
      containers:
        - name: champ-user-consumer
          image: asia.gcr.io/poc-innovation-iot/champ-user-consumer:TAG
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: champ-user-consumer-secret-env
          volumeMounts:
              - mountPath: /config/config.yaml
                name: champ-user-consumer-configmap-file
                subPath: config.yaml
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            timeoutSeconds: 10
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            timeoutSeconds: 10
            initialDelaySeconds: 10
          resources:
            limits:
              cpu: 64m
              memory: 64Mi
            requests:
              cpu: 32m
              memory: 32Mi
      volumes:
        - name: champ-user-consumer-configmap-file
          configMap:
            name: champ-user-consumer-configmap-file