apiVersion: v1
kind: Service
metadata:
  name: champ-user-consumer
  labels:
    app.kubernetes.io/name: champ-user-consumer
    app.kubernetes.io/instance: champ-user-consumer
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: champ-user-consumer
    app.kubernetes.io/instance: champ-user-consumer
